export const dataMenu = [
  {
    id: 1,
    title: 'Burger',
    img: 'burger',
  },
  {
    id: 2,
    title: 'Pizza',
    img: 'pizza',
  },
  {
    id: 3,
    title: 'Sandwich',
    img: 'sandwich',
  },
  {
    id: 4,
    title: 'Fruts',
    img: 'strawberry',
  },
];

export const dataProducts = [
  {
    id: 1,
    name: 'Beef Burger',
    img: 'beef_big_size',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
  },
  {
    id: 2,
    name: 'Chicken Burger',
    img: 'beef_chicken',
    taste: 'Spicy',
    price: '100000',
    group_type: 1,
  },
  {
    id: 3,
    name: 'Seafood Burger',
    img: 'seafood_beef',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
  },
  {
    id: 4,
    name: 'Double Beef Burger',
    img: 'two_tier_beef_bib_size',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
  },
  {
    id: 5,
    name: 'Beef Cheese Burger',
    img: 'two_tier_beef',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
  },
  {
    id: 6,
    name: 'Beef Burger',
    img: 'beef_big_size',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
  },
  {
    id: 7,
    name: 'Chicken Burger',
    img: 'beef_chicken',
    taste: 'Spicy',
    price: '100000',
    group_type: 1,
  },
  {
    id: 8,
    name: 'Seafood Burger',
    img: 'seafood_beef',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
  },
  {
    id: 9,
    name: 'Double Beef Burger',
    img: 'two_tier_beef_bib_size',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
  },
  {
    id: 10,
    name: 'Beef Cheese Burger',
    img: 'two_tier_beef',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
  },
  {
    id: 11,
    name: 'Beef Cheese Burger',
    img: 'two_tier_beef',
    taste: 'Spicy',
    price: '8',
    group_type: 2,
  },
];

export const dataProductsDetail = [
  {
    id: 1,
    name: 'Beef Burger',
    img: 'beef_big_size',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    name: 'Chicken Burger',
    img: 'beef_chicken',
    taste: 'Spicy',
    price: '100000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 3,
    name: 'Seafood Burger',
    img: 'seafood_beef',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 4,
    name: 'Double Beef Burger',
    img: 'two_tier_beef_bib_size',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 5,
    name: 'Beef Cheese Burger',
    img: 'two_tier_beef',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 6,
    name: 'Beef Burger',
    img: 'beef_big_size',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 7,
    name: 'Chicken Burger',
    img: 'beef_chicken',
    taste: 'Spicy',
    price: '100000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 8,
    name: 'Seafood Burger',
    img: 'seafood_beef',
    taste: 'Spicy',
    price: '80000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 9,
    name: 'Double Beef Burger',
    img: 'two_tier_beef_bib_size',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 10,
    name: 'Beef Cheese Burger',
    img: 'two_tier_beef',
    taste: 'Spicy',
    price: '120000',
    group_type: 1,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
  {
    id: 11,
    name: 'Beef Cheese Burger',
    img: 'two_tier_beef',
    taste: 'Spicy',
    price: '8',
    group_type: 2,
    description: 'Description for all products',
    extra_food: [1, 2, 3, 4, 5],
  },
];

export const dataExtraFood = [
  {
    id: 1,
    name: 'Beef',
    img: 'beef',
  },
  {
    id: 2,
    name: 'Salad',
    img: 'salad',
  },
  {
    id: 3,
    name: 'Purple Onion',
    img: 'purple_onion',
  },
  {
    id: 4,
    name: 'Tomato',
    img: 'tomato',
  },
  {
    id: 5,
    name: 'Cheese',
    img: 'cheese',
  },
];
