export default {
  BottomTabNavigator: 'BottomTabNavigator',
  RoutesNavigator: 'RoutesNavigator',
  CarouselScreen: 'CarouselScreen',
  WelcomeScreen: 'WelcomeScreen',
  HelloScreen: 'HelloScreen',
  HomeScreen: 'HomeScreen',
  ProductsDetailScreen: 'ProductsDetailScreen',
  HeartScreen: 'HeartScreen',
  CartScreen: 'CartScreen',
  Logging: 'Logging',
  UserScreen: 'UserScreen',
  SearchScreen: 'SearchScreen',
  DetailCardSearch: 'DetailCardSearch',
  LoginScreen: 'LoginScreen',
};
