export default {
  BottomTabNavigator: 'BottomTabNavigator',
  BottomNavigation: 'BottomNavigation',
  RoutesNavigator: 'RoutesNavigator',
  CarouselScreen: 'CarouselScreen',
  WelcomeScreen: 'WelcomeScreen',
  HomeScreen: 'HomeScreen',
  ProductsDetailScreen: 'ProductsDetailScreen',
  HeartScreen: 'HeartScreen',
  CartScreen: 'CartScreen',
  Logging: 'Logging',
  UserScreen: 'UserScreen',
  SearchScreen: 'SearchScreen',
  DetailCardSearch: 'DetailCardSearch',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  OTPScreen: 'OTPScreen',
  ResetPasswordScreen: 'ResetPasswordScreen',
};
